### ISSUE TITLE
Large Button misplacement.

### ISSUE THREAD

**Issue by MacMeDan** [HsoiEnterprises/HELargeCenterTabBarController#11]
So when I hide the tab bar when pushing to a view and then navigate back the large button image renders in the top left corner. Is there a way to fix it so that it renders back on the tab bar?

Thank you.

**Comment by hsoi** [comment]
Hrm. Interesting.

Can you provide a project that reproduces the problem?

**Comment by MacMeDan** [comment]
Ya I will do that.

**Comment by fusionconsulting** [comment]
Any updates on this? I'm seeing the same thing.

**Comment by hsoi** [comment]
@digital-dog since @MacMeDan hasn't provided a reproducible case, can you?

**Comment by hsoi** [comment]
@MacMeDan @digital-dog As I've not heard back and am unable to reproduce this problem, I'm going to close this issue.

I did just release v2.1.0 which added some autolayout changes to help with iOS 11 and the safe area. It may be worth checking that out.

If the issue persists, if a reproducible case can be provided, we can repoen this issue.
