### ISSUE TITLE
Transparency on center button

### ISSUE THREAD

**Issue by Kowaio** [HsoiEnterprises/HELargeCenterTabBarController#4]
Hello,

Sorry to bother you with this but I tried your example and fell in love with this. However I was wondering because I tried to add it to a sample project of mine, using cocoapods but I have an issue with transparency for the main button.

Here's a screenshot: http://cl.kowaio.me/image/1j3y3V1R0f1p

The only different thing I've done is use subclass in order not to load the images from the AppDelegate. 
Thanks a lot for your answer.

Best regards,

**Comment by Kowaio** [comment]
Hmm. My bad, as you explained in your readme, the dispatch_async is needed to ensure that the parent views are loaded. I thought using a subclass was enough, since my viewDidLoad called the super.viewDidLoad but anyway, addind the dispatch_async call before loading the images worked for me. Sorry about that.

**Comment by hsoi** [comment]
Just now waking up and reading this.

Glad you were able to get it going!

Thank you for using the library. :smile:
